// Country detection extendido (200+ aliases) para normalizar location_raw
// libre de Indeed/LinkedIn/Workday/scrapers hacia ISO 3166-1 alpha-2.
// Fallback a job_apis.detectCountry() — que trae un mapa pequeño usado en
// la legacy path (~15 países).

const ALIASES = {
  NZ: ['new zealand','nueva zelanda','aotearoa','auckland','wellington','christchurch','hamilton','dunedin','tauranga','palmerston north','queenstown','napier','whangarei'],
  AU: ['australia','australian','sydney','melbourne','brisbane','perth','adelaide','canberra','hobart','darwin','gold coast','newcastle','wollongong','geelong','townsville','cairns'],
  ES: ['spain','españa','espana','spanish','madrid','barcelona','valencia','sevilla','seville','zaragoza','málaga','malaga','bilbao','alicante','córdoba','cordoba','granada','murcia','palma','las palmas'],
  US: ['united states','usa','new york','nyc','california','texas','florida','seattle','boston','chicago','san francisco','los angeles','washington dc','atlanta','miami','dallas','austin','houston','denver','phoenix','portland','san diego','philadelphia'],
  GB: ['united kingdom','great britain','england','scotland','wales','northern ireland','london','manchester','birmingham','edinburgh','glasgow','leeds','liverpool','bristol','cambridge','oxford','belfast','sheffield','cardiff','reading','brighton'],
  IE: ['ireland','éire','eire','dublin','cork','galway','limerick'],
  DE: ['germany','deutschland','berlin','munich','münchen','hamburg','frankfurt','cologne','köln','stuttgart','düsseldorf','dusseldorf','leipzig','bremen'],
  FR: ['france','paris','lyon','marseille','toulouse','nice','nantes','bordeaux','lille','strasbourg','montpellier','rennes'],
  IT: ['italy','italia','italian','rome','roma','milan','milano','turin','torino','florence','firenze','naples','napoli','bologna','venice','venezia'],
  NL: ['netherlands','holland','amsterdam','rotterdam','the hague','den haag','utrecht','eindhoven','groningen'],
  BE: ['belgium','belgique','bélgica','brussels','bruxelles','antwerp','antwerpen','ghent','gent','liège','liege'],
  CH: ['switzerland','suisse','suiza','zurich','zürich','geneva','genève','bern','basel','lausanne','lucerne'],
  AT: ['austria','wien','vienna','salzburg','graz','innsbruck'],
  SE: ['sweden','sverige','stockholm','gothenburg','göteborg','malmö','uppsala'],
  NO: ['norway','norge','oslo','bergen','trondheim','stavanger'],
  FI: ['finland','suomi','helsinki','espoo','tampere','turku'],
  DK: ['denmark','danmark','copenhagen','københavn','aarhus','odense'],
  PT: ['portugal','lisbon','lisboa','porto','braga','coimbra','faro'],
  PL: ['poland','polska','warsaw','warszawa','kraków','krakow','wrocław','wroclaw','gdańsk','gdansk','poznań','poznan'],
  CZ: ['czech','česko','prague','praha','brno','ostrava'],
  HU: ['hungary','magyar','budapest','debrecen'],
  GR: ['greece','hellas','athens','athína','thessaloniki'],
  RO: ['romania','rumania','bucharest','bucurești','cluj'],
  BG: ['bulgaria','sofia'],
  HR: ['croatia','hrvatska','zagreb','split'],
  SI: ['slovenia','ljubljana'],
  SK: ['slovakia','bratislava'],
  LT: ['lithuania','vilnius','kaunas'],
  LV: ['latvia','riga','rīga'],
  EE: ['estonia','tallinn','tartu'],
  IS: ['iceland','reykjavik','reykjavík'],
  LU: ['luxembourg','luxemburg'],
  MT: ['malta','valletta'],
  CY: ['cyprus','nicosia','limassol'],
  CA: ['canada','toronto','vancouver','montreal','montréal','calgary','ottawa','edmonton','quebec','québec','winnipeg','halifax'],
  MX: ['mexico','méxico','mexican','cdmx','guadalajara','monterrey','puebla','tijuana','querétaro','queretaro'],
  BR: ['brazil','brasil','são paulo','sao paulo','rio de janeiro','brasília','brasilia','belo horizonte','curitiba','porto alegre','florianópolis','florianopolis'],
  AR: ['argentina','buenos aires','rosario','mendoza'],
  CL: ['chile','santiago','valparaíso','valparaiso','concepción','concepcion'],
  CO: ['colombia','bogotá','bogota','medellín','medellin','cali','cartagena'],
  PE: ['peru','perú','lima','arequipa','cusco'],
  UY: ['uruguay','montevideo'],
  PY: ['paraguay','asunción','asuncion'],
  BO: ['bolivia','la paz','santa cruz','cochabamba'],
  EC: ['ecuador','quito','guayaquil','cuenca'],
  VE: ['venezuela','caracas','maracaibo'],
  CR: ['costa rica','san josé'],
  PA: ['panama','panamá'],
  GT: ['guatemala'],
  HN: ['honduras','tegucigalpa'],
  SV: ['el salvador','san salvador'],
  NI: ['nicaragua','managua'],
  DO: ['dominican republic','república dominicana','santo domingo'],
  CU: ['cuba','havana','la habana'],
  PR: ['puerto rico'],
  JP: ['japan','japón','tokyo','osaka','kyoto','yokohama','nagoya','sapporo','fukuoka'],
  CN: ['china','beijing','shanghai','shenzhen','guangzhou','chengdu','hangzhou','wuhan'],
  HK: ['hong kong','香港'],
  TW: ['taiwan','taipei','kaohsiung'],
  KR: ['south korea','seoul','busan','incheon'],
  SG: ['singapore','singapura'],
  MY: ['malaysia','malasia','kuala lumpur','penang','johor'],
  TH: ['thailand','tailandia','bangkok','chiang mai','phuket'],
  VN: ['vietnam','viet nam','hanoi','ho chi minh','saigon','da nang','hai phong'],
  PH: ['philippines','filipinas','manila','cebu','davao','makati','pasay','taguig','quezon city'],
  ID: ['indonesia','jakarta','surabaya','bandung','bali','denpasar'],
  IN: ['india','bangalore','bengaluru','mumbai','delhi','hyderabad','chennai','pune','kolkata','gurgaon','gurugram','noida','ahmedabad','kochi'],
  PK: ['pakistan','karachi','lahore','islamabad','rawalpindi'],
  BD: ['bangladesh','dhaka','chittagong'],
  LK: ['sri lanka','colombo'],
  NP: ['nepal','kathmandu'],
  KZ: ['kazakhstan','almaty','astana'],
  UZ: ['uzbekistan','tashkent'],
  IR: ['iran','tehran'],
  IQ: ['iraq','baghdad'],
  IL: ['israel','tel aviv','jerusalem','haifa'],
  SA: ['saudi arabia','arabia saudí','riyadh','jeddah','mecca','medina','dammam'],
  AE: ['uae','united arab emirates','emirates','dubai','abu dhabi','sharjah'],
  QA: ['qatar','doha'],
  KW: ['kuwait'],
  BH: ['bahrain','manama'],
  OM: ['oman','muscat'],
  JO: ['jordan','amman'],
  LB: ['lebanon','beirut'],
  SY: ['syria','damascus','aleppo'],
  TR: ['turkey','türkiye','istanbul','ankara','izmir','antalya','bursa'],
  RU: ['russia','moscow','st. petersburg','saint petersburg','novosibirsk','yekaterinburg'],
  UA: ['ukraine','kyiv','kiev','lviv','odesa','kharkiv'],
  DZ: ['algeria','algérie','argelia','algiers','alger','oran','constantine','annaba','blida','batna'],
  MA: ['morocco','maroc','marruecos','casablanca','rabat','marrakech','fez','fès','tangier','tanger','agadir'],
  TN: ['tunisia','tunisie','túnez','tunis'],
  LY: ['libya','tripoli','benghazi'],
  EG: ['egypt','egipto','cairo','alexandria','giza'],
  SD: ['sudan','khartoum'],
  ET: ['ethiopia','addis ababa'],
  KE: ['kenya','nairobi','mombasa'],
  UG: ['uganda','kampala'],
  TZ: ['tanzania','dar es salaam','dodoma'],
  RW: ['rwanda','kigali'],
  NG: ['nigeria','lagos','abuja','kano','ibadan'],
  GH: ['ghana','accra','kumasi'],
  SN: ['senegal','dakar'],
  CM: ['cameroon','cameroun','yaoundé','douala'],
  ZA: ['south africa','johannesburg','cape town','pretoria','durban'],
  NA: ['namibia','windhoek'],
  ZW: ['zimbabwe','harare'],
  ZM: ['zambia','lusaka'],
  BW: ['botswana','gaborone'],
  MZ: ['mozambique','maputo'],
  AO: ['angola','luanda'],
  MG: ['madagascar','antananarivo'],
  MU: ['mauritius','port louis'],
};

function detectCountry(locationRaw) {
  if (!locationRaw) return null;
  const l = locationRaw.toLowerCase();
  for (const [iso, aliases] of Object.entries(ALIASES)) {
    for (const a of aliases) if (l.includes(a)) return iso;
  }
  return null;
}

module.exports = { detectCountry, ALIASES };
